image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - vendor/bin/phpunit
