image: php:7.2

stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php --filename=composer --install-dir=/usr/local/bin
    - composer install
    - vendor/bin/phpunit
